version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx.prod
    ports:
      - '9001:80'
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile-php.prod
    depends_on:
      - db
  db:
    image: mysql:5.7.26
    env_file:
      - ./docker/mysql/.env
    ports:
      - '3308:3306'
    volumes:
      - db-data-test:/var/lib/mysql

volumes:
  db-data-test:
    driver: local
