version: '3'

services:
  web:
    image: nginx:1.16.1-alpine
    ports:
      - '9000:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7.19
    env_file:
      - ./docker/mysql/.env
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
