# --------------------------------------------------------------------------------
# Compile Assets (Mix)
# --------------------------------------------------------------------------------
FROM node:12.12.0-alpine AS builder

COPY ./laravel /var/laravel

WORKDIR /var/laravel

RUN npm install \
    && npm rebuild node-sass \
    && npm run production

# --------------------------------------------------------------------------------
# Main Stage
# --------------------------------------------------------------------------------
FROM nginx:1.16.1-alpine

COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /var/laravel/public /var/www/laravel/public
